" Highlight current line 
set cursorline
" Highlight current line in bold
hi CursorLine term=bold cterm=bold

" Place yanked text in global clipboard to allow
" copy and paste between different vim instances 
" (needs vim compiled with clipboard support)
set clipboard=unnamedplus 
" Automatically stop auto-indenting when pasting in insert mode.
" (https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode)
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
function! XTermPasteBegin()
	set pastetoggle=<Esc>[201~
	set paste
	return ""
endfunction

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" Spell checking by default for latex, tex and markdown
autocmd FileType latex,tex,markdown,md setlocal spell 

" Plug-ins
call plug#begin()
" Snazzy theme (same as I use in terminal)
Plug 'connorholyday/vim-snazzy'
" Git in vim
Plug 'tpope/vim-fugitive'
" Airline status bar
Plug 'vim-airline/vim-airline'
" Airline themes
Plug 'vim-airline/vim-airline-themes'
" File type icons
Plug 'ryanoasis/vim-devicons'
Plug 'lervag/vimtex'
call plug#end()

" Fallback to latex when file type ambiguous
let g:tex_flavor = 'latex'

" A solution I don't understand to a problem I don't understand
" (Without this termguicolors freaks)
" https://github.com/vim/vim/issues/993#issuecomment-25565160://github.com/vim/vim/issues/993#issuecomment-255651605
" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

set termguicolors
syntax enable
colorscheme snazzy

" Theme of statusline
let g:airline_theme = 'base16_snazzy'
let g:airline_section_z = ''
let g:airline_powerline_fonts = 1

" Press F5 to execute script with program specified in the shebang line
nnoremap <F5> :!"%:p" <Enter>

" Stop double spacing after a period
set nojoinspaces

set tw=79
